---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - 'App Store'
  - Calendar
  - Contacts
  - FaceTime
  - Keynote
  - Launchpad
  - Maps
  - Mail
  - Messages
  - Music
  - News
  - Notes
  - Numbers
  - Pages
  - Photos
  - Podcasts
  - Siri
  - Safari
  - Reminders
  - Stickies
  - 'System Preferences'
  - TV
dockitems_persist:
  - name: "Settings"
    path: "/Applications/System Preferences.app/"
    pos: 2
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 3
  - name: "Firefox Developer Edition"
    path: "/Applications/Firefox Developer Edition.app/"
    pos: 4
  - name: "WebStorm"
    path: "/Applications/WebStorm.app/"
    pos: 5
  - name: "PhpStorm"
    path: "/Applications/PhpStorm.app/"
    pos: 6
  - name: "Iterm"
    path: "/Applications/Iterm.app/"
    pos: 7
  - name: 'screenshots'
    path: '~/Pictures/screenshots/'
  - name: 'Downloads'
    path: '~/Downloads/'

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/supercoffee/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .config/karabiner/karabiner.json

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - ansible
  - bash-completion
  - cloc
  - curl
  - doctl
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - gpg
  - iperf
  - imagemagick
  - libevent
  - sqlite
  - mcrypt
  - mysql
  - mysql-client
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - s3cmd
  - wget
  - wrk
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - google-chrome
  - android-commandlinetools
  - balenaetcher
  - clion
  - cyberduck
  - darktable
  - datagrip
  - db-browser-for-sqlite
  - docker
  - firefox
  - firefox-developer-edition
  - hammerspoon
  - handbrake
  - intellij-idea
  - iterm2
  - karabiner-elements
  - libreoffice
  - macdown
  - ngrok
  - owasp-zap
  - paw
  - phpstorm
  - postman
  - rectangle
  - slack
  - sourcetree
  - the-unarchiver
  - transmission
  - ultimaker-cura
  - unclack
  - viscosity
  - visual-studio-code
  - webstorm
  - wireshark

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: [ ]
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: [ ]
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: [ ]
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: [ ]
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: [ ]
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: [ ]
