---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
    src: https://github.com/supercoffee/ansible-role-dotfiles
    version: master

collections:
  - name: geerlingguy.mac
