---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: ensure osx dotfile is executable
  file:
    path: "~/.osx"
    mode: 0744

- name: Run .osx dotfiles.
  command: "{{ osx_script }}"
  changed_when: false
